# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# optional: 
name: clone-xray
on: 
 workflow_dispatch: 
 release:
    types: [created]

jobs:        
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux]
        goarch: ["386", amd64, arm64, mips, mipsle]
    steps:
    - uses: actions/checkout@v3
    - name: Cloning repo
      run: |
        rm -rf ./{,.[!.],..?}*
        git clone https://github.com/XTLS/Xray-core ./tmp
        #  git clone -b fix  https://github.com/yuhan6665/Xray-core/ ./tmp
    - uses: wangyoucao577/go-release-action@v1.35
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./tmp/main"
        binary_name: "xray"
        ldflags: "-s -w -buildid="
        overwrite: true
        release_name: "xray" 
        executable_compression: "upx --ultra-brute"
        build_flags: "-trimpath"
        pre_command: "CGO_ENABLED=0"
        
       
